# Start from ROS base image
FROM ros:humble-ros-base

# Set the working directory
WORKDIR /

# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    ros-humble-joint-state-publisher \
    ros-humble-robot-state-publisher \
    #ros-humble-gazebo-plugins \
    ros-humble-teleop-twist-keyboard \
    ros-humble-teleop-twist-joy \
    ros-humble-xacro \
    ros-humble-urdf \
    software-properties-common \
    ros-humble-rviz2 \
    python3-dev \
    python3-rpi.gpio \
    ros-humble-rmw-cyclonedds-cpp \
    && rm -rf /var/lib/apt/lists/*

# Make a catkin workspace
RUN mkdir -p /ros2_ws/src
WORKDIR /ros2_ws/src

# Download Tortoisebot repo
RUN git clone -b ros2-humble https://github.com/rigbetellabs/tortoisebot.git 

# Install dependencies
RUN apt-get update && apt-get install ros-humble-camera-info-manager -y


# Reemplazar el archivo bringup.py ya que no se dispone del raspicam
RUN rm -rf /ros2_ws/src/tortoisebot/tortoisebot_bringup/launch/bringup.launch.py /ros2_ws/src/tortoisebot/tortoisebot_gazebo/ /ros2_ws/src/tortoisebot/v4l2_camera/


WORKDIR /ros2_ws/src/tortoisebot 
RUN cd YDLidar-SDK/build && cmake .. && make && sudo make install



# Build your ROS packages
WORKDIR /ros2_ws
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && colcon build --symlink-install --parallel-workers 1"

COPY launch/bringup.launch.py /ros2_ws/src/tortoisebot/tortoisebot_bringup/launch/

RUN rm -rf /ros2_ws/src/tortoisebot/tortoisebot_description/models/urdf/tortoisebot_simple.xacro

COPY urdf/tortoisebot_simple.xacro /ros2_ws/src/tortoisebot/tortoisebot_description/models/urdf/tortoisebot_simple.xacro

RUN /bin/bash -c "source /opt/ros/humble/setup.bash && colcon build --symlink-install --parallel-workers 1"


# Source the workspace every time a new shell is opened in the container
RUN echo source /ros2_ws/install/setup.bash >> ~/.bashrc

# Set the entry point to start a bash shell
WORKDIR /
COPY ros_bringup_entrypoint.sh /
RUN chmod +x ros_bringup_entrypoint.sh
ENTRYPOINT ["/ros_bringup_entrypoint.sh"]
