version: '3'

services:

  tortoisebot-ros2-real:
    #image: morg1207/morg1207-cp15:tortoisebot-ros2-real
    build: 
      context: .
      dockerfile: dockerfile_tortoisebot-ros2-real
    image: morg1207/morg1207-cp15:tortoisebot-ros2-real
    container_name: tortoisebot_ros2_real_cont
    network_mode: host
    privileged: true
    tty: true
    devices:
      # lidar
      - /dev/ttyUSB0:/dev/ttyUSB0
      # Camara
      - /dev/video0
      - /dev/video1
      - /dev/video2
      - /dev/video3
      - /dev/video4
      - /dev/video5
    volumes:
      # Me permite acceder a los recursos de la pantalla
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Me permite acceder a los pines
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - ROS_DOMAIN_ID=1

  tortoisebot-ros2-slam-real:
    #image: morg1207/morg1207-cp15:tortoisebot-ros2-slam
    build:    
      context: .
      dockerfile: dockerfile_tortoisebot-ros2-slam-real
    image: morg1207/morg1207-cp15:tortoisebot-ros2-real-slam
    container_name: tortoisebot_ros2_real_slam_cont
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=1
    depends_on:
      - tortoisebot-ros2-real